/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api("org.apache.commons:commons-text:1.10.0")
    api(project(":tock-translator-core"))
    api("com.google.cloud:google-cloud-translate:2.3.5")
}

description = "Tock Google Translator"
