/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api("com.google.apis:google-api-services-chat:v1-rev132-1.25.0")
    api("com.google.oauth-client:google-oauth-client:1.34.1")
    api("com.google.http-client:google-http-client-apache-v2:1.42.3")
    api("com.google.http-client:google-http-client-jackson2:1.42.3")
    api("com.google.auth:google-auth-library-oauth2-http:1.11.0")
    api("com.fasterxml.jackson.core:jackson-core:2.13.4")
    api("com.fasterxml.jackson.core:jackson-databind:2.13.4.2")
    api("org.assertj:assertj-core:3.16.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation("io.vertx:vertx-codegen:4.3.4")
}

description = "Tock Bot Google Chat Connector"
