/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":bot-toolkit-base"))
    api(project(":tock-bot-connector-iadvize"))
    api(project(":tock-bot-connector-messenger"))
    api(project(":tock-bot-connector-ga"))
    api(project(":tock-bot-connector-google-chat"))
    api(project(":tock-bot-connector-alexa"))
    api(project(":tock-bot-connector-slack"))
    api(project(":tock-bot-connector-rocketchat"))
    api(project(":tock-bot-connector-twitter"))
    api(project(":tock-bot-connector-whatsapp"))
    api(project(":tock-bot-connector-teams"))
    api(project(":tock-bot-connector-businesschat"))
    api(project(":tock-bot-connector-web"))
    api("com.squareup.okhttp3:okhttp:4.10.0")
    api("com.squareup.okhttp3:okhttp-urlconnection:4.10.0")
    api("com.squareup.okhttp3:logging-interceptor:4.10.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
}

description = "Tock Bot Toolkit"
