/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api("org.jetbrains.kotlin:kotlin-reflect:1.7.20")
    api(project(":tock-bot-engine"))
    api(project(":tock-bot-engine-jackson"))
    api(project(":tock-bot-connector-rest"))
    api(project(":tock-bot-storage-mongo"))
    api(project(":tock-translator-noop"))
    api(project(":tock-stt-noop"))
    api("com.squareup.okhttp3:okhttp:4.10.0")
    api("com.squareup.okhttp3:okhttp-urlconnection:4.10.0")
    api("com.squareup.okhttp3:logging-interceptor:4.10.0")
}

description = "Tock Bot Toolkit Base"
