/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api("org.litote.chat.rocket.sdk:core:3.5.1")
    api("org.litote.chat.rocket.sdk:common:3.5.1")
    api("org.json:json:20220924")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation("io.vertx:vertx-codegen:4.3.4")
}

description = "Tock Bot Rocket Chat Connector"
