language: java
os: linux
dist: bionic
jdk:
  - openjdk8
branches:
  only:
    - master
    - /^build-.*$/
install: mvn versions:display-property-updates --projects .
script: travis_wait 40 ./etc/deploy.sh
cache:
  directories:
  - $HOME/.m2/repository
  - nlp/admin/web/node_modules
  - bot/admin/web/node_modules
before_cache:
  - rm -rf $HOME/.m2/repository/ai/tock
  - rm -rf bot/admin/web/node_modules/tock-nlp-admin
env:
  global:
    - secure: "TxejqbmKVE22rfI7qUV1hShIssSvzC7Tk1qf3LQZ45dmc4JsWIW5ficjf+zwDvo2ZRYMms4LhAWN5mYoApUUf//GjwIdBibIY6G7tb3Kmlj+5V49i2TCO2Lx080e7XMEe7EgjGHzLblgMpYMqwcWKOWXqUTvO8gZVHt5r8Aadad5fBjNUg4hkmHBtGr/Io78t6JXAcuvVNaaZRGpTx6MW8g6KwIcMhZ+VQWaYdS0nmvZqbn591XNciq4uou3c/o131gBymrzSX0OXS8Slf7i12U5Kp69Ee7FLD82v7ofOQEsMElgmg6ju2iAd2j0bBI6kIV4JeoilsNQR9VHkwG46tG8O+CQNpUC1Jn8xlhEqBAVogbT54wS2UG9wCQO501D1ggDYywsC+8ZmeF5HMXtvKd+n9TfPaQ8UKAvJx5xdLcxDHdM2nn8EjQ95Ge980GO1iy3f0W7qsYqq6R122Kj3pevzVtxUwcPYxbwjvZANhiOjbtm3vLPLC6ilCxZ3ap6bYN8en+eWs84fUdPyrnBzC4tHqV75dT6TeHWnwTdJtgZR0jOIUfLWg/IZ7zDp714WOwthzlt8Zp7Th6+EC8n3Bsmd+2Yps+yHh5iuuDBRpV8FYhtonTkoEDXg7FnzD8dyvxALXw/Wj90iDJMI9Mr3a8iUl40MUn5cSa9DCpZmQM="
    - secure: "o2jxph7cLfqFUrlk4LgWZXIHj0oRxDLUgLQLNj5+w4HbChenFiiGcqjw0wClmcg3NjJtIFdaOgeRerJCFFchGSB8afjnsvmUOKPMkfVZmdzSgg+BXZe35sLAdXmrGt0uooZbYdDdfqNWJJqjJRopHGXiH4QU3CD8SS7RmQcFIJSWI86q6GaadZF0FaZC4KyYD5ynXwuG4s1lPqbOgOLmtED59KczWDQoRaUxjL6AVUDLkrA7x0QwUJZMpOKkZwd7G8g1b5M8QTKCZ4sZqbrAI0mXxUUMuwwIF6zLC8T/WeWSysw0MO62DHoh6UgLXmmSTPXjtF6ux4ampay797olJrZT065B3BpEXlwp7/kLdsG4iOUbYXuMcyXRw5301dqaFnoN3Pas/+pszyZ2VE3HS503l+BJ8refLjZsVsfVDwwcMX6OsuES/Wd3GnPUhofs6zYa191IRMpxTc78NkttGUL/UvzOQGnOTu97K8W5Ml4L6qCCZnxMHEe7v4t/IF6JI8rYuOFrOv1+3M8J2jhBDyTDFkHunSeyNe1VlQI8D1BBzZRyhSDTHZhSBd0CZm6zXjixyCbrJvt0ecPErq47rYdSrQ275uIp8N0JNsCAk9bEhJkzgzJ2FIxghmW0hFoTSq+/uyIPaSHWMMRoH5HpdzXvCHINtgTa5FZMhGx1mWw="
    - secure: "HLbmch4aIEzGhnS2AI+Z6jfjIfARaD038p/jPfIhZ1g1VaDmWJR/UwiA+pnmOD2w1gPEPwTG+7FXwouaIx4AhDauVUpF3rJiPRkb/vRO2PfkHfhybbedjMLryvjeuJvID8SQvCaXyX6dJyPWV+g+s3p8Er4ZQAgATYvE5SyLgrkCDdY6acDb+5qZjpoOQrVDmN+djV0QByAU1a7zgGPHXK7zXp6EE/roi3zUYAKmIgia39cwum47fgzip/61oSprzHoI/i3B5MNbz+ffpfSrWcou6O1CpjP+so80Jc83ACI34oY4WoIjQkdgWht7aPGzahdV8fnKIu7AMagBufhr6C2kCMSOhfaOJY3feAWqVg5jR+4o44QpE6ppbvDUP9CIUlXM63Ps1xmFxAhOku7kp4zHr4wFQ/Z3Aho0WeKH3ssLH5FJ4993V1WhHr5ZY3XIrN5c0k/yaRmysEJ3Ql30w5CzpzSq7FCZtgZikXPgDcj77q7p3wiPyLlMl0gESBGuWgAixhki7XjjVlZYIseJW7UEpfw/CYwVHDpBBQt31y9l18+AZjZMXedZSEDFj/mGrlxhJ1Ke3xlsrnrV2GLwKzpQdQ2e5Yog/YDtaAZXBAlMuro0u4HlfxRiEaV6y2lPuDlDMSfStBOIBx9S/IuxlA3tSDhOGm/sxURNCafZRXI="
    - secure: "cEIVcb1kJoS1wxckNx3cOzRHw1KF2BWF80JzE4tSj/2qaRSCd3S9A9KOOJ1umAazeh1hX8WJt7wayTrpRvLgJyDKkYiDu6l3cx8JBXS6ACgUAMIFJUAw+TSPRYEQxpdAwZrXL4ULdHsc9yCQOycA2OeZ+qifgZF5Qb7pkcPC/FkJYZvyn1XI8yVwrw6VPRXbKXW/5WcCbjX/cEtzi6MOdRhj++MtQo6KLpOgjOLA6DTSh6KfQbCkUf2vz9XHYLu2ntEBBCi9LaCHie9OqJH/rbbr4O7h0y4Ak7Ed+1xVfejDo8TwxWnklSM7QjaSHjrCRXqsVoYocsfl68Mp5vHaZ2B7muYimTXdquQ7egdWd+wk7zjY9Q9LSMs9hyjngmeqKZ3cWVk1gAPqJJgWz0vSkybcDAuqDyZUoiZ9GgGb6JM4FxcDcWTF6EwakIl7VYELnwccSMBNC/6J+IBV+CuS1bHqu68K6+pvjyZitn47syyuOESr5QnLQsS//zzlE8C7lBHNcbWMJpJf3KQAvSvbIZiiwa1CHkkEbaSDqIJBPPmmgLWTN1lUXJk8oKWGZR+TvfyAT9pFXswfUvI32xIsnJcIBdmYeoxVUMBheYS2qtln9f6K1CJeVmd3UeQiYHe3DzJJVAo4na+ByABHHaq9hWkyh7Nedk8m6NgaTYUsVTk="
after_success:
  - ./etc/trigger-travis.sh
