/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-api-model"))
    api(project(":bot-toolkit"))
    api(project(":tock-nlp-front-client"))
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
}

description = "Tock Bot API Service"
