/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine"))
    api("org.litote.kmongo:kmongo:4.7.2")
    api("org.litote.kmongo:kmongo-async:4.7.2")
    api("org.jasypt:jasypt:1.9.3")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("org.litote.kmongo:kmongo-flapdoodle:4.7.2")
    testImplementation(project(":tock-shared"))
}

description = "Tock Bot Mongo"
