/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":bot-toolkit-base"))
    api(project(":tock-shared"))
    api("ch.tutteli.atrium:atrium-cc-en_GB-robstoll:0.15.0")
    api("io.mockk:mockk-jvm:1.13.2")
//initial conversion (not working)
//    providedCompile(project(":bot-toolkit"))
    compileOnly(project(":bot-toolkit"))
    compileOnly("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    compileOnly("junit:junit:4.13.2")
    compileOnly("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    compileOnly("org.junit.jupiter:junit-jupiter-api:5.9.1")
    compileOnly("org.junit.jupiter:junit-jupiter-params:5.9.1")
}

description = "Tock Bot Test Toolkit Base"
