/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-shared"))
    api("com.google.guava:guava:31.1-jre")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation(project(":tock-shared"))
}

description = "Tock Translator Core"
