/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api(project(":tock-stt-core"))
    api("org.apache.commons:commons-lang3:3.12.0")
    api("com.squareup.retrofit2:converter-scalars:2.9.0")
    api("se.akerfeldt:okhttp-signpost:1.1.0")
    api("oauth.signpost:signpost-core:1.2.1.2")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation(project(":tock-shared"))
    testImplementation("org.assertj:assertj-core:3.22.0")
}

description = "Tock Bot Twitter Connector"
