/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api(project(":tock-bot-connector-whatsapp"))
    api(project(":tock-bot-connector-messenger"))
    api("com.fasterxml.jackson.core:jackson-core:2.13.4")
    api("com.fasterxml.jackson.core:jackson-databind:2.13.4.2")
    api("org.assertj:assertj-core:3.16.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation("io.vertx:vertx-codegen:4.3.4")
}

description = "Tock Bot Alcmeon Connector"
