/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-api-model"))
    api(project(":bot-toolkit-base"))
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
}

description = "Tock Bot WS Client API"
