/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-shared"))
    testImplementation(project(":tock-shared"))
}

description = "Tock STT Core"
