/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api("commons-codec:commons-codec:1.15")
    api("com.google.guava:guava:31.1-jre")
}

description = "Tock Bot Business Chat Connector"
