/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api("com.squareup.retrofit2:retrofit:2.9.0")
    api("com.squareup.okhttp3:logging-interceptor:4.10.0")
    api("com.squareup.okhttp3:okhttp:4.10.0")
    api("com.squareup.retrofit2:converter-jackson:2.9.0")
    api("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4")
    api("com.fasterxml.jackson.core:jackson-databind:2.13.4.2")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4")
    api("com.google.guava:guava:31.1-jre")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
}

description = "Tock Bot Rest Connector Client"
