/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-nlp-core-client"))
    api(project(":tock-nlp-front-shared"))
    api("com.vdurmont:emoji-java:5.1.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
}

description = "Tock NLP Front Service"
