/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-connector-web-model"))
    api(project(":tock-bot-engine-jackson"))
    api(project(":tock-bot-orchestration"))
    api("org.litote.kmongo:kmongo:4.7.2")
    api("org.litote.kmongo:kmongo-async:4.7.2")
    api("org.commonmark:commonmark:0.20.0")
    testImplementation(project(":tock-shared"))
    testImplementation("org.assertj:assertj-core:3.22.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
}

description = "Tock Bot Web Connector"
