version: 1

disable_existing_loggers: False

formatters:
    simple:
        (): colorlog.ColoredFormatter
        format: "%(log_color)s%(asctime)s.%(msecs)03d %(levelname)s %(module)s - %(funcName)s - %(lineno)d: %(message)s %(reset)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
        log_colors:
            WARNING: yellow
            ERROR: red
            CRITICAL: black,bg_red

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    llm_orchestrator:
        level: INFO
        handlers: [console]
        propagate: no
    uvicorn:
        level: INFO
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console]
