/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-api-webhook-base"))
    api(project(":bot-toolkit"))
}

description = "Tock Bot API Webhook"
