/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-nlp-model-service"))
    api("org.apache.opennlp:opennlp-tools:2.0.0")
}

description = "Tock NLP OpenNlp"
