/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4")
    api("com.fasterxml.jackson.core:jackson-databind:2.13.4.2")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4")
}

description = "Tock Bot Web Connector Model"
