/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-nlp-model-client"))
    api(project(":tock-nlp-core-client"))
    api(project(":tock-nlp-model-opennlp"))
    api(project(":tock-nlp-model-service"))
    api(project(":tock-nlp-model-storage-mongo"))
    api(project(":tock-nlp-core-service"))
    api(project(":tock-nlp-front-client"))
    api(project(":tock-nlp-front-service"))
    api(project(":tock-nlp-front-storage-mongo"))
    api(project(":tock-nlp-duckling-client"))
}

description = "Tock NLP Front Ioc"
