/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-admin-kotlin-compiler-shared"))
    api(project(":tock-shared"))
    api("org.jetbrains.kotlin:kotlin-reflect:1.7.20")
    api("org.jetbrains.kotlin:kotlin-compiler:1.7.20")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
}

description = "Tock Kotlin Compiler Core"
