/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-nlp-entity-value"))
    api(project(":tock-bot-engine"))
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
}

description = "Tock Bot API Model"
