/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-nlp-admin-server"))
    api(project(":bot-toolkit"))
    api(project(":tock-bot-connector-rest-client"))
    api("org.apache.commons:commons-csv:1.9.0")
    api(project(":tock-bot-admin-test-core"))
    api(project(":tock-bot-admin-kotlin-compiler-client"))
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
}

description = "Tock Bot Admin Server"
