/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api(project(":tock-stt-core"))
    api("org.jasypt:jasypt:1.9.3")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation(project(":tock-stt-google-speech"))
}

description = "Tock Bot WhatsApp Connector"
