/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api("commons-codec:commons-codec:1.15")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("com.google.guava:guava:31.1-jre")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation(project(":tock-shared"))
}

description = "Tock Bot Messenger Connector"
