/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api("com.github.salomonbrys.kodein:kodein:4.1.0")
    api("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4")
    api("com.fasterxml.jackson.core:jackson-databind:2.13.4.2")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4")
    api("org.litote.kmongo:kmongo-id-jackson:4.7.2")
    api("org.litote.jackson:jackson-module-loader:0.4.0")
    api("org.litote.jackson:jackson-data:0.4.0")
    api("io.github.microutils:kotlin-logging-jvm:3.0.3")
    api("org.slf4j:slf4j-api:2.0.3")
    api("ch.qos.logback:logback-classic:1.4.4")
    api("org.slf4j:jul-to-slf4j:2.0.3")
    api("com.google.guava:guava:31.1-jre")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.6.4")
    api("org.pac4j:pac4j-core:5.7.0")
    api("org.pac4j:pac4j-cas:5.7.0")
    api("org.pac4j:vertx-pac4j:6.0.1")
    api("io.vertx:vertx-auth-common:4.3.4")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    compileOnly("org.jasypt:jasypt:1.9.3")
    compileOnly("io.vertx:vertx-web:4.3.4")
    compileOnly("io.vertx:vertx-auth-jwt:4.3.4")
    compileOnly("io.vertx:vertx-auth-oauth2:4.3.4")
    compileOnly("io.vertx:vertx-codegen:4.3.4")
    compileOnly("org.litote.kmongo:kmongo:4.7.2")
    compileOnly("org.litote.kmongo:kmongo-async:4.7.2")
    compileOnly("com.squareup.retrofit2:retrofit:2.9.0")
    compileOnly("com.squareup.okhttp3:logging-interceptor:4.10.0")
    compileOnly("com.squareup.okhttp3:okhttp:4.10.0")
    compileOnly("com.squareup.retrofit2:converter-jackson:2.9.0")
    compileOnly("io.github.resilience4j:resilience4j-retrofit:1.7.1")
    compileOnly("org.litote.kmongo:kmongo-flapdoodle:4.7.2")
    compileOnly("org.apache.xmlgraphics:batik-transcoder:1.12")
    compileOnly("org.apache.xmlgraphics:batik-codec:1.12")
    compileOnly("org.apache.xmlgraphics:batik-dom:1.12")
}

description = "Tock Shared"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
