/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-admin-test-core"))
    api(project(":tock-xray-plugin"))
    api(project(":tock-bot-engine-jackson"))
    api("com.beust:klaxon:5.6")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
}

description = "Tock Bot Admin Test Xray"
