sudo: required
services:
  - docker
language: java
jdk:
- openjdk8
branches:
  only:
  - master
env:
  global:
  - secure: "PEALvqQx5qgQ2hZRAJSV2nbcHvVJom3e+eyEWAmNuOzmHtf/f9bOyy3koUbmPYSQB1+uxjTEsGpbnFGlT5qtrkDJm/mL8T41YfYd0lpot3BeiLp+GB6zVxQQiU+S1C0rQ3XayLq2LEdV0ssnk08qNjVW1pp6GmKX/R/iEA/6wzbWu8CQ3SzZxvz4AaY0Bj+u+7JMtgIiyf3ebc48smNvNCrUsY9Z0Nap3zPLninNuJzZtTYkP5xsSvlI/jUkzukzLWLstIaSjJBeGakOjsxSF9TGbvIVcH72tj6NcT2bpUCzMo93Dyx9K9uK75XffEpk8ERbF2kPHA+V+vPjrdVfwK3mFgbJ1W4ibSk7snsN4xp/sUwH2p0Zf6/B7COrfY1N9q8PC1XxZAvAP+8JayzKEiByxo+Kn3Anwn98V44un7cdLxrhD+1+n2pcZmmP4C86bZZRM0clLGY2fuXeLHRNZ/YO4BrXk20brsRBcjl5JfcPVWOBQ25ldLmDtpRXO+wGEuda9g0VP5c8sdmOqVowe7eBvR5+dn27fOMvXOaD3GclJlwoF6i70qMMRGTwJ41xdjboGq6JFOl46UWhcsxOBAwk85y4cPsVecWN+3QNoRGquGmqwCLprfmKnmEuCl1cRu/oI6z8NoxVfJhhdy76Ezf0L5vA3swk6VVsvwfbGFs="
  - secure: "CayiJSveeyTeaUKnr0+22pFAP2SsWfXr/l0ZvhcY/DQcuO1VuJW2pmvQlPqpx45FZGoAVoYjm5mhUQS+2FuGmXtknOon4u5dsFRdtW6ylyj0GVOq1U4baiILA0gp67lHD1lDHFBrOmSIHLC9WfEyUw4j7t6YoNEbaATbhS/VaYxAxIutiIy2OxfW1gUXt/uw2sBsLA6HeiCW3H4+wzviilIJUl0GSLaqGhV0DvP4EoWIHfLuNreHdgNQWk2lb7jIMFmf9PxuLLBgbar+QXQqWEXGV3dYHblzXQx9bHY7CX05lMjSJQB8KznUOBvv9oSRQbKPf/esIRlm7CK0qxmwhM6vk/odzN53fuDpxFvvmRp4F+mhcONxFHETzezi8/9fI9IrGa9QZicILJe+NLRnHwAh0juXR+iD6AygGFQnrc45kFbwj2F2HUlBEshlTWE2SAYP2Zl86Ax5ID01lIMa/C+pVme7yjZhqBDS92Khbgb6EE2Is0pgwPlFo8rtXtgisBmccbIsYHwc4gqChDONM8VwE1ijZXaR+7MYqpBC6qmJGp7JptCJ/EzD+EaSwwUlOw01/YpjCo4vtgCfjdqmY8vpF2losXQOAbai8W/JSPFjTsMPWa1f0p6Wnj9o7vqlGNH0W9Ej29iQhlXPD1kc7L0Fn3f7PycoErUnQpoj1S0="
after_success:
- "./etc/deploySnapshot.sh"