/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api("io.vertx:vertx-web:4.3.4")
    system("wit:duckling:0.4.23")
}

description = "Tock Duckling Entities Service"
