/*
 * This file was generated by the Gradle 'init' task.
 */

configurations {
    create("duckling-standalone")
}

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api("io.vertx:vertx-web:4.3.4")
//    system("wit:duckling:0.4.23")
    "duckling-standalone"(fileTree("lib") { include("duckling-*-standalone.jar") })
}

description = "Tock Duckling Entities Service"
