/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-nlp-model-shared"))
    api("com.google.guava:guava:31.1-jre")
}

description = "Tock NLP Model Service"
