/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine-jackson"))
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    api("com.nimbusds:nimbus-jose-jwt:9.25.6")
    api("com.microsoft.bot:bot-integration-core:4.14.3")
    api("com.google.code.gson:gson:2.10")
    api("net.minidev:json-smart:2.4.8")
    api("com.fasterxml.jackson.core:jackson-core:2.13.4")
    api("com.fasterxml.jackson.core:jackson-annotations:2.13.4")
    api("com.fasterxml.jackson.core:jackson-databind:2.13.4.2")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4")
    api("com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.4")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4")
    api("com.fasterxml.jackson.datatype:jackson-datatype-joda:2.13.4")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.10.0")
}

description = "Tock Bot Teams Connector"
