/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-admin-kotlin-compiler-core"))
    api(project(":bot-toolkit"))
    api("io.vertx:vertx-web:4.3.4")
}

description = "Tock Kotlin Compiler Server"
