/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-stt-core"))
    api("com.fasterxml.jackson.core:jackson-core:2.13.4")
    api("ws.schild:jave-core:3.3.1")
    api("ws.schild:jave-nativebin-linux64:3.3.1")
    api("com.google.cloud:google-cloud-speech:2.6.0")
}

description = "Tock Google Speech STT"
