/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-shared"))
    api(project(":tock-nlp-front-client"))
    api(project(":tock-translator-noop"))
    api("io.vertx:vertx-web:4.3.4")
    api("io.vertx:vertx-auth-common:4.3.4")
    api(project(":tock-nlp-front-ioc"))
    api("io.vertx:vertx-auth-jwt:4.3.4")
    api("io.vertx:vertx-auth-oauth2:4.3.4")
    api("org.apache.commons:commons-csv:1.9.0")
}

description = "Tock NLP Admin Server"
