/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-shared"))
    api(project(":tock-nlp-front-client"))
    api(project(":tock-nlp-build-model-worker-on-demand"))
    api(project(":tock-nlp-build-model-worker-on-aws-batch"))
    api("io.vertx:vertx-web:4.3.4")
    api(project(":tock-nlp-front-ioc"))
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
}

description = "Tock NLP Build Model Worker"
