/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-bot-engine"))
    api(project(":tock-bot-storage-mongo"))
    api(project(":tock-nlp-front-ioc"))
    api("com.google.cloud:google-cloud-dialogflow:4.9.0")
    api("com.google.auth:google-auth-library-oauth2-http:1.11.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.7.20")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.9.1")
}

description = "Tock NLP Dialogflow Client"
