/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":tock-shared"))
    api("io.vertx:vertx-web:4.3.4")
}

description = "Tock NLP Build Model Worker on compute platform"
