/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.tock.java-conventions")
}

dependencies {
    api(project(":bot-toolkit"))
    api(project(":bot-test-base"))
}

description = "Tock Bot Test Toolkit"
