name: Maven test

on:
    push:
        branches:
          - master
          - contribution/*
          - feature/*
env:
  SHARED: shared
  STT: stt/core,stt/noop,stt/google-speech
  TRANSLATOR: translator/core,translator/noop,translator/google-translate
  ENGINE: bot/engine,bot/engine-jackson
  ORCHESTRATION: bot/orchestration
  CONNECTOR: bot/connector-rest,bot/connector-rest-client,bot/connector-messenger,bot/connector-alcmeon,bot/connector-ga,bot/connector-slack,bot/connector-alexa,bot/connector-rocketchat,bot/connector-twitter,bot/connector-whatsapp,bot/connector-teams,bot/connector-businesschat,bot/connector-web,bot/connector-web-model,bot/connector-google-chat,bot/connector-iadvize
  STORAGE: bot/storage-mongo
  TOOLKIT: bot/toolkit-base,bot/toolkit
  TEST: bot/test-base,bot/test
  COMPILER: bot/admin/kotlin-compiler/shared,bot/admin/kotlin-compiler/core,bot/admin/kotlin-compiler/client,bot/admin/kotlin-compiler/server
  ADMIN: bot/admin/test/core,bot/admin/server
  API: bot/api/model,bot/api/service,bot/api/client,bot/api/webhook-base,bot/api/webhook,bot/api/websocket-base,bot/api/websocket,bot/api/retrofit-jackson-client

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
          cache: maven
      - name: Build
        run: mvn --batch-mode --update-snapshots -Dskip.npm -Dassembly.skipAssembly=true -DskipTests clean install
      - name: Test
        run:  mvn  --batch-mode --update-snapshots -Dskip.npm -Dassembly.skipAssembly=true test
